version: '3.9'
services:
  mysql:
    restart: always
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-8-0-28
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: staffs
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./docker/mysql-volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 15
  backend:
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    build: .
    container_name: spring-boot-backend
    ports:
      - 8080:8080
volumes:
  mysql-volume: